# Generated by Django 3.1.1 on 2020-09-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=60)),
                ('tz', models.CharField(blank=True, max_length=256)),
                ('activity_periods', models.ManyToManyField(blank=True, related_name='activity_periods', to='ManApi.UserActivity')),
            ],
        ),
    ]
