# Generated by Django 3.1.1 on 2020-09-24 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='u_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ManApi.user'),
        ),
    ]
